### ISSUE TITLE
Página Inicial

### ISSUE THREAD

**Issue by LucasCNS** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-1-e1-proj-web-t3-bref#15]
Tela inicial com fontes corretas

**Comment by brunoruas2** [comment]
Quais as fontes usadas no mockup mesmo?

**Comment by LucasCNS** [comment]
Paleta de cores: 
Amarelo #FFC300
Marrom #483A20

Background #FFFFFF(Branco) ou #FFFFFA(Branco Amarelado)

Fontes:
BREF = Oswald
Lato para o resto dos textos.

**Comment by brunoruas2** [comment]
Vou preparar a página com as fontes corretas.

**Comment by brunoruas2** [comment]
![image](https://user-images.githubusercontent.com/16859514/166074709-e68e119f-f3bb-4164-9319-c64272e069dd.png)

Fontes corretas inseridas.
