### ISSUE TITLE
Padronização do desenvolvimento

### ISSUE THREAD

**Issue by LucasCNS** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-1-e1-proj-web-t3-bref#22]
Espaço para definir os padrões de layout das páginas.

**Comment by LucasCNS** [comment]
Proposta de padronização dos botões:

button {
    margin: 5px 0px 2px 0px;
    border-radius: 4px;
    border: 0px;
    width: 250px;
    padding: 10px;
    cursor: pointer;
    transition: 0.8s all;
    color: #FFF;
    background: #483A20;
}

button:hover {
    background: rgb(110, 79, 22);
    transform: scale(1.01);
}

**Comment by LucasCNS** [comment]
Proposta de padronização dos inputs:

input {
    width: 325px;
    margin: 3px;
    padding:10px;
    border-radius: 4px;
    text-indent: 0.1rem;
    border-width: 1px;
    outline: 0;
    border-style: solid;
    background-color: #FFFFF4;
}

**Comment by dieguinsharp** [comment]
Padrão de nomenclatura em todo o projeto -> lowerCamelCase.
Nome de arquivos com letra minuscula, exceto nome composto:
telaInicial, reserva
